#!/bin/sh

# Loading the modules needed by my app:
# modprobe 8188eu
 
# Launching my app:

python /root/webpage.py &          # <-- Don't forget the "&" otherwise other system stuff won't start until you leave your app !!!
echo "Server is running!"

exit 0